cmake: add missing library to tests
The dl library is a private dependency since 7071343c58e7
(cmake: set implementation-only dependencies as private) but the build
is broken on Ubuntu 16.04 (but the same GCC version works on Travis CI):

    /usr/bin/ld:
    CMakeFiles/test_service_loader.dir/service_loader_test.cpp.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
    //lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status

Fix it by linking the missing ld library with the test executable.